apiVersion: apps/v1
kind: Deployment
metadata:
  name: new-test-app-deploy
  labels:
    type: restapi
spec:
  selector: 
    matchLabels:
      app: new-test-app
  replicas: 3
  template:
    metadata:
      name: new-test-app-tmpl
      labels:
        app: new-test-app
    spec:
      containers:
        - name: new-test-app
          image: whitepatrick/new-test-app:latest
          ports:
            - containerPort: 5000